# Generated by Django 4.1.9 on 2023-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imagesapp", "0002_rename_images_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="total_likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(fields=["-total_likes"], name="imagesapp_i_total_l_18a2e0_idx"),
        ),
    ]
